#!/bin/bash

# resolves all dependencies that the application requires to run

set -e

cd "$(dirname "$0")/.."

# make sure bundler installed
which bundler 2>&1 >/dev/null || gem install bundler

# make sure needed gems installed
bundle check --path vendor/gems 2>&1 >/dev/null || bundle install --path vendor/gems --quiet

# install scripts
rake
